name: Test with Pytest 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: tests run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and setup
        uses: actions/checkout@v3
      - name: Set working directory
        run: cd https://github.com/fredrikkri/oblig3/tree/3d3245ea7e0a97fa010f6b5a9713b20f2ca44b08
        working-directory: path/to/your/project

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install poetry
        run: pipx install poetry

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: tests run
        run: pytesttest -r wr w