name: Test with Pytest 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: tests run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and setup
        uses: actions/checkout@v2

      - name: Set working directory
        run: cd oblig3
        working-directory: ./oblig3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: tests run
        run: pytest