name: Test with Pytest 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: tests run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and setup
        uses: actions/checkout@v2

      - name: Set working directory
        run: |
          cd https://github.com/fredrikkri/oblig3/tree/3d3245ea7e0a97fa010f6b5a9713b20f2ca44b08
        working-directory: https://github.com/fredrikkri/oblig3/tree/3d3245ea7e0a97fa010f6b5a9713b20f2ca44b08

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: tests run
        run: pytest